### ISSUE TITLE
一些问题 && 解决方法

### ISSUE THREAD

**Issue by lucyking** [lucyking/ndk-two-libs#2]
## 编译libfirst.so工具不对：
- arm-none-eabi-gcc，apk运行时提示：
```uses variable-size enums yet the output is to use 32-bit enums; use of enum values across objects ma... ...```

- arm-linux-gnueabi-gcc，apk运行时提示:
```empty/missing DT_HASH in  (built with --hash-style=gnu?)......```

解决方法：
- 需要用Android.mk编译

## 出现绝对路径
- 是因为项目路径不对

## 需要Load所有的so库：
```   
static {
        try {
            System.loadLibrary("first");
            System.loadLibrary("second");
        } catch (UnsatisfiedLinkError e) {
        }
}
```

**Comment by lucyking** [comment]
- 注意按照调用关系依次System.loadLibrary(*.so)
- 顺序不对时出错：

>System.loadLibrary("second");
System.loadLibrary("first");
            


```
01-25 14:14:23.312 18081-18081/? E/art: dlopen("/data/app/com.example-1/lib/arm/libfirst.so", RTLD_LAZY) failed: dlopen failed: empty/missing DT_HASH in "libfirst.so" (built with --hash-style=gnu?)
01-25 14:14:23.312 18081-18081/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example, PID: 18081
                                                   java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libfirst.so" (built with --hash-style=gnu?)
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                       at java.lang.System.loadLibrary(System.java:988)
                                                       at com.example.twolibs.TwoLibs.onCreate(TwoLibs.java:38)
                                                       at android.app.Activity.performCreate(Activity.java:6073)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2569)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:162)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5513)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```


```
01-25 14:22:33.547 18434-18434/com.example.twolibs E/art: dlopen("/data/app/com.example.twolibs-1/lib/arm/libsecond.so", RTLD_LAZY) failed: dlopen failed: library "Y:/work/NDK/two-libs_newBegin_0124/two-libs_newBegin_0124/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libfirst.so" not found
01-25 14:22:33.557 18434-18434/com.example.twolibs E/art: No implementation found for int com.example.twolibs.TwoLibs.add(int, int) (tried Java_com_example_twolibs_TwoLibs_add and Java_com_example_twolibs_TwoLibs_add__II)
01-25 14:22:33.557 18434-18434/com.example.twolibs E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.example.twolibs, PID: 18434
                                                                     java.lang.UnsatisfiedLinkError: No implementation found for int com.example.twolibs.TwoLibs.add(int, int) (tried Java_com_example_twolibs_TwoLibs_add and Java_com_example_twolibs_TwoLibs_add__II)
                                                                         at com.example.twolibs.TwoLibs.add(Native Method)
                                                                         at com.example.twolibs.TwoLibs.onCreate(TwoLibs.java:46)
                                                                         at android.app.Activity.performCreate(Activity.java:6073)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2569)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:162)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5513)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```
